### ISSUE TITLE
Release Planning v0.0.6

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#115]
I would like to do a maintenance release here within the following 2-3 weeks with a version that is usable again on the current work state without friction.

TODOs:
- [x] Fix broken dependencies, `ethereumjs-common` update, PR #111
- [x] `ethereumjs-devp2p` update to `v3.0.0`
- [x] `ethereumjs-util` `v7.0.2` update, PR #129 
- [x] Broader general dependency update
- [ ] Optional: update `libp2p` dependencies
- [x] Bring README up-to-date, PR #114 
- [x] Some basic connectivity and error message fixes during sync test, e.g. #113, likely 1-2 more
- [x] Manually test browser example from [README](https://github.com/ethereumjs/ethereumjs-client)
- [x] Move CI from Travis to GitHub Actions, @ryanio, PR #119
- [x] Optional if scope is realistic: karma browser testing or a very simple first E2E browser test setup, see also #108

**Comment by holgerd77** [comment]
Closed by #135
