### ISSUE TITLE
Prepare for migration to EthereumJS Monorepo

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-client#142]
Those are some of the requirements to move this lib to the VM monorepo:
- [x] Migrate to TypeScript, #144 
- [ ] Rename `lib` folder to `src`
- [x] Remove coveralls configuration
- [x] Integrate @ethereumjs/config v2.0.0 shared configuration, #151, #152, #153
- [x] Remove Babel configuration (to be replaced by Typescript build), #144 
- [x] Unify Readme and package.json with the monorepo standards

**Comment by holgerd77** [comment]
Closed by https://github.com/ethereumjs/ethereumjs-vm/pull/973
